version: '3'
services: 
  app:
    build: . 
    container_name: application-server
    environment:
      - FLASK_APP=app_server
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
    ports:
      - 8080:5000
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
