version: '3'
services: 
  app:
    build: . 
    container_name: application-server
    environment:
      - FLASK_APP=app_server
      - FLASK_ENV=development
      - FLASK_RUN_PORT=3000
    ports:
      - 5000:3000
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
